---
name: fcast_project
channels: [conda-forge, nodefaults]
dependencies:
  - python ==3.12
  - pip >=21.1

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask >=0.5.0
  - pytask-latex >=0.4.2
  - pytask-parallel >=0.5.0
  - pytest
  - pytest-cov
  - pytest-xdist

  # Python template project dependencies
  - statsmodels
  - numpy
  - pandas >=2.2
  - plotly >=5.2.0,<6
  - matplotlib
  - seaborn
  - scikit-learn
  - pathlib
  - openpyxl
  - pyarrow >=10.0.1
  - pygraphviz
  - sqlalchemy
  - psycopg2-binary

  # Install project
  - pip: [pdbp, kaleido, xgboost]
